title:             Maycol Sanchez Salazar
email:             mayc1030@gmail.com
description:       A Blog msscode
author:             Maycol Sanchez Salazar
baseurl:           "/testmsscode"
url:               "https://mayc1030.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
